name: Final Project V2
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - name: Run API Tests
        run: ./gradlew runApi
      - name: Run Web Tests
        run: ./gradlew runWeb
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Laporan-Final-Project-Lengkap
          path: target/